# Generated by Django 3.2.4 on 2021-08-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposicion',
            name='detalleExposicion',
            field=models.ManyToManyField(to='Visita.DetalleExposicion'),
        ),
        migrations.AddField(
            model_name='exposicion',
            name='fechaFin',
            field=models.DateField(default="2020-02-02"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obra',
            name='duracionResumida',
            field=models.DurationField(default="0"),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='horarioEmpleado',
        ),
        migrations.AddField(
            model_name='empleado',
            name='horarioEmpleado',
            field=models.ManyToManyField(to='Visita.HorarioEmpleado'),
        ),
    ]
