# Generated by Django 3.2.4 on 2021-08-02 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Visita', '0002_auto_20210802_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detalleexposicion',
            name='lugarAsignado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Visita.cargo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='codigoValidacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cuit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='domicilio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaIngreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='horarioEmpleado',
            field=models.ManyToManyField(blank=True, to='Visita.HorarioEmpleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='mail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sedeDondeTrabaja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Visita.sede'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sexo',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='domicilio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='mail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='telefCelular',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='telfFijo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exposicion',
            name='detalleExposicion',
            field=models.ManyToManyField(blank=True, to='Visita.DetalleExposicion'),
        ),
        migrations.AlterField(
            model_name='exposicion',
            name='fechaFin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exposicion',
            name='fechaFinReplanificada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exposicion',
            name='fechaInicioReplanificada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exposicion',
            name='publicoDestino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Visita.publicodestino'),
        ),
        migrations.AlterField(
            model_name='exposicion',
            name='tipoExposicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Visita.tipoexposicion'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='alto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='ancho',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='codigoSensor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fechaPrimerIngreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='valuacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicodestino',
            name='caracteristicas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservavisita',
            name='cantidadAlumnos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservavisita',
            name='cantidadAlumnosConfirmada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservavisita',
            name='duracionExtendida',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservavisita',
            name='fechaHoraCreacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservavisita',
            name='fechaHoraReserva',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservavisita',
            name='horaFinReal',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservavisita',
            name='horaInicioReal',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservavisita',
            name='numeroReserva',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='fechaFin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='fechaFinVigencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipoexposicion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='caducidad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
