# Generated by Django 3.2.4 on 2021-08-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visita', '0003_auto_20210802_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='tarifa',
        ),
        migrations.AddField(
            model_name='sede',
            name='tarifa',
            field=models.ManyToManyField(to='Visita.Tarifa'),
        ),
    ]
