# Generated by Django 3.2.4 on 2021-08-02 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Visita', '0004_auto_20210802_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='cambioEstado',
            field=models.ManyToManyField(blank=True, null=True, to='Visita.CambioEstado'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='empleado',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Visita.empleado'),
        ),
    ]
