# Generated by Django 3.2.4 on 2021-08-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visita', '0005_auto_20210802_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='cambioEstado',
            field=models.ManyToManyField(blank=True, to='Visita.CambioEstado'),
        ),
    ]
