# Generated by Django 3.2.4 on 2021-08-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Visita', '0006_alter_obra_cambioestado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservavisita',
            old_name='duracionExtendida',
            new_name='duracionEstimada',
        ),
    ]
