# Generated by Django 3.2.4 on 2021-08-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visita', '0007_rename_duracionextendida_reservavisita_duracionestimada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
