# Generated by Django 3.2.4 on 2021-08-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visita', '0009_auto_20210807_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservavisita',
            name='asignacionGuia',
        ),
        migrations.AddField(
            model_name='reservavisita',
            name='asignacionGuia',
            field=models.ManyToManyField(to='Visita.AsignacionVisita'),
        ),
        migrations.RemoveField(
            model_name='reservavisita',
            name='cabioEstado',
        ),
        migrations.AddField(
            model_name='reservavisita',
            name='cabioEstado',
            field=models.ManyToManyField(to='Visita.CambioEstado'),
        ),
        migrations.RemoveField(
            model_name='reservavisita',
            name='exposicion',
        ),
        migrations.AddField(
            model_name='reservavisita',
            name='exposicion',
            field=models.ManyToManyField(to='Visita.Exposicion'),
        ),
    ]
