# Generated by Django 3.2.4 on 2021-08-08 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Visita', '0011_auto_20210808_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambioestado',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Visita.estado'),
        ),
        migrations.AlterField(
            model_name='cambioestado',
            name='fechaHoraFin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cambioestado',
            name='fechaHoraInicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
