# Generated by Django 3.2.4 on 2021-08-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visita', '0013_auto_20210808_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='nombreObra',
            field=models.CharField(max_length=50),
        ),
    ]
